const test = require("node:test");
const assert = require("node:assert/strict");
const { readFileSync } = require("node:fs");
const { join } = require("node:path");

const { renderHtml } = require("../dist/render-html.js");

function readClientSource(...segments) {
  return readFileSync(join(__dirname, "../src/client", ...segments), "utf8");
}

function readRuntimeSource(fileName) {
  return readClientSource("runtime", fileName);
}

test("renderHtml loads external client assets and bootstrap config", () => {
  const html = renderHtml({
    host: "127.0.0.1",
    port: 4181,
    explicitProjects: false,
    projects: [{ root: "/tmp/project", label: "project" }]
  });

  assert.match(html, /<link rel="stylesheet" href="\/client\/app\.css\?v=/);
  assert.match(html, /<script src="\/client\/app\.js\?v=.*"><\/script>/);
  assert.match(html, /window\.__AGENTS_OFFICE_CLIENT_CONFIG__/);
  assert.match(html, /"sceneDefinitions":\{/);
});

test("renderHtml can bootstrap a discovered fleet project list distinct from the seed options", () => {
  const html = renderHtml(
    {
      host: "127.0.0.1",
      port: 4181,
      explicitProjects: false,
      projects: [{ root: "/tmp/seed", label: "Seed" }]
    },
    [
      { root: "/tmp/seed", label: "Seed" },
      { root: "/tmp/discovered", label: "Discovered" }
    ]
  );

  assert.match(html, /"root":"\/tmp\/seed","label":"Seed"/);
  assert.match(html, /"root":"\/tmp\/discovered","label":"Discovered"/);
});

test("renderHtml includes the global split-worktrees toggle", () => {
  const html = renderHtml({
    host: "127.0.0.1",
    port: 4181,
    explicitProjects: false,
    projects: [{ root: "/tmp/project", label: "project" }]
  });

  assert.match(html, /id="split-worktrees-button"/);
  assert.match(html, /Split Worktrees/);
});

test("client bootstrap runs the generated runtime module instead of evaling a source string", () => {
  const indexSource = readClientSource("index.ts");
  const runtimeModuleSource = readClientSource("app-runtime.ts");

  assert.ok(indexSource.includes('import { startClientApp } from "./app-runtime";'));
  assert.ok(indexSource.includes("startClientApp();"));
  assert.doesNotMatch(indexSource, /new Function\(/);
  assert.match(
    runtimeModuleSource,
    /^\/\/ @ts-nocheck\n\/\/ Generated by packages\/web\/scripts\/generate-runtime-module\.mjs/m
  );
  assert.ok(runtimeModuleSource.includes("export function startClientApp(): void {"));
});

test("client runtime keeps current local desk-live work on a workstation through notLoaded transport gaps", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.doesNotMatch(layoutSource, /const CURRENT_LOCAL_LIVE_WORKSTATION_GRACE_MS = 8000;/);
  assert.doesNotMatch(layoutSource, /return agent\.isOngoing === true \|\| hasCurrentLocalDeskGrace\(agent\);/);
  assert.match(
    seatingSource,
    /const CURRENT_LOCAL_LIVE_WORKSTATION_GRACE_MS = 8000;/
  );
  assert.match(
    seatingSource,
    /function hasCurrentLocalDeskGrace\(agent\) {\n\s+const updatedAt = parseAgentUpdatedAt\(agent && agent\.updatedAt\);/
  );
  assert.match(
    seatingSource,
    /if \(agent\.statusText === "notLoaded"\) {\n\s+if \(agent\.state === "done"\) {\n\s+const updatedAt = parseAgentUpdatedAt\(agent\.updatedAt\);/
  );
  assert.match(
    seatingSource,
    /return agent\.isCurrent === true\n\s+&& Number\.isFinite\(updatedAt\)\n\s+&& Date\.now\(\) - updatedAt <= workstationDoneGraceMs\(agent\);/
  );
  assert.match(
    seatingSource,
    /return agent\.isOngoing === true \|\| hasCurrentLocalDeskGrace\(agent\);/
  );
});

test("client runtime keeps active local desks live, leaves waiting in the rec area, and gives current idle/done work a short settle window", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.doesNotMatch(layoutSource, /if \(agent\.state === "waiting"\) {\n\s+return false;\n\s+}/);
  assert.match(
    seatingSource,
    /function hasCurrentLocalSeatCooldown\(agent\) {\n\s+const updatedAt = parseAgentUpdatedAt\(agent && agent\.updatedAt\);/
  );
  assert.match(
    seatingSource,
    /if \(agent\.statusText === "active"\) {\n\s+if \(agent\.state === "waiting"\) {\n\s+return false;\n\s+}\n\s+if \(\(agent\.state === "idle" \|\| agent\.state === "done"\) && hasCurrentLocalSeatCooldown\(agent\)\) {\n\s+return true;\n\s+}\n\s+return agent\.isCurrent === true\n\s+&& agent\.state !== "idle"\n\s+&& agent\.state !== "done";/
  );
});

test("client runtime only keeps ordinary local desks for current workload", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.match(seatingSource, /if \(agent\.isCurrent !== true\) {\n\s+return false;/);
  assert.doesNotMatch(layoutSource, /if \(agent\.isCurrent !== true\) {\n\s+return false;/);
  assert.doesNotMatch(seatingSource, /const recentlyLive = Number\.isFinite\(updatedAt\)/);
});

test("runtime source keeps desk seats stable when a second workstation appears in a pod", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(sceneSource.includes("const tile = sceneTileSize(compact);"));
  assert.ok(sceneSource.includes("const leftCellX = 0;"));
  assert.ok(sceneSource.includes("const rightCellX = Math.max(0, entry.slot.width - cellWidth);"));
  assert.ok(sceneSource.includes("const seatMirrored = hasBothSides"));
  assert.ok(sceneSource.includes("const cellX = seatMirrored ? rightCellX : leftCellX;"));
  assert.ok(sceneSource.includes("mirrored: seatMirrored,"));
});

test("runtime source keeps running and validating workers seated at their workstation", () => {
  const renderSource = readRuntimeSource("render-source.ts");

  assert.ok(renderSource.includes('if (state === "running" || state === "validating") {'));
  assert.ok(renderSource.includes('if (state === "blocked") {'));
  assert.ok(renderSource.includes("tileHeight: 1"));
});

test("runtime source preserves workstation entering-reveal flags for the Pixi flicker animation", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");

  assert.ok(sceneSource.includes("enteringReveal: options.enteringReveal === true,"));
  assert.ok(sceneSource.includes("enteringReveal: shouldRevealWorkstation(snapshot.projectRoot, agent, entry.slot.id),"));
  assert.ok(sceneSource.includes("enteringReveal: shouldRevealWorkstation(snapshot.projectRoot, entry.agent, entry.slot.id),"));
  assert.ok(sceneSource.includes("function shouldRevealWorkstation(projectRoot, agent, slotId) {"));
  assert.ok(sceneSource.includes("const previousSceneState = renderedAgentSceneState.get(key) || null;"));
  assert.ok(sceneSource.includes("return previousSlotId !== slotId;"));
  assert.ok(
    navigationSource.includes('if (!screenshotMode && definition.enteringReveal === true) {\n            sprite.visible = false;\n          }')
  );
  assert.ok(
    navigationSource.includes('renderer.animatedSprites.push({\n              kind: "blink",\n              nodes: enteringRevealNodes,')
  );
});

test("workspace focus reuses compact scene geometry and grid-snapped desk starts", () => {
  const uiSource = readRuntimeSource("ui-source.ts");
  const renderSource = readRuntimeSource("render-source.ts");
  const sceneGridSource = readClientSource("scene-grid-source.ts");

  assert.ok(uiSource.includes("compact: true,"));
  assert.ok(
    sceneGridSource.includes('const deskStartColumn = Math.max('),
    "desk columns should start from a snapped tile column"
  );
  assert.ok(
    sceneGridSource.includes('const deskStartX = deskStartColumn * config.tileSize;'),
    "desk pod origins should convert the snapped column back into tile pixels"
  );
  assert.ok(
    renderSource.includes("tileHeight: 1"),
    "workstation footprint should occupy only the bottom row"
  );
});

test("workspace focus lets the expanded floor fill the full panel rect", () => {
  const stylesSource = readFileSync(
    join(__dirname, "../src/client/styles.css"),
    "utf8"
  );

  assert.match(
    stylesSource,
    /body\.workspace-focus \.workspace-tower,\n\s+body\.workspace-focus \.workspace-tower-single \{\n\s+width: 100%;\n\s+max-width: none;\n\s+min-height: 100%;\n\s+margin: 0;/
  );
  assert.match(
    stylesSource,
    /body\.workspace-focus \.tower-floor-body \{\n\s+min-height: 0;\n\s+height: 100%;\n\s+padding: 0;\n\s+overflow: hidden;/
  );
  assert.match(
    stylesSource,
    /body\.workspace-focus \.office-map-host \{\n\s+min-height: 0;\n\s+height: 100%;\n\s+overflow: hidden;/
  );
});

test("runtime source strips markdown formatting markers from display text", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");

  assert.ok(layoutSource.includes("function stripDisplayMarkdown(value) {"));
  assert.ok(layoutSource.includes('.replace(/\\\\[([^\\\\]]+)\\\\]\\\\(([^)]+)\\\\)/g, "$1")'));
  assert.ok(layoutSource.includes('.split(String.fromCharCode(96)).join("")'));
  assert.ok(layoutSource.includes("const plainText = stripDisplayMarkdown(normalized);"));
  assert.ok(layoutSource.includes('const next = plainText.indexOf("/mnt/", index);'));
  assert.ok(layoutSource.includes("output += plainText.slice(index, next) + (cleaned || wslToWindowsPath(candidate));"));
});

test("runtime source section files now start on function boundaries instead of continuing previous functions", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.match(sceneSource, /^export const CLIENT_RUNTIME_SCENE_SOURCE = `\s*function buildLeadClusters/);
  assert.match(uiSource, /^export const CLIENT_RUNTIME_UI_SOURCE = `\s*function renderSessions/);
});

test("runtime source merges worktrees by repo and renders worktree badges in hover and split floor headers", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const renderSource = readRuntimeSource("render-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");
  const settingsSource = readRuntimeSource("settings-source.ts");

  assert.ok(layoutSource.includes("function mergeWorktreeProjects(projects) {"));
  assert.ok(layoutSource.includes('return "git-common:" + commonGitDir;'));
  assert.ok(layoutSource.includes("sourceProjectRoot,"));
  assert.ok(renderSource.includes('const worktreeHtml = worktreeName'));
  assert.ok(renderSource.includes('class="agent-hover-worktree"'));
  assert.ok(sceneSource.includes('tower-floor-title tower-floor-title-worktree'));
  assert.ok(settingsSource.includes("splitWorktrees: Boolean(parsed && parsed.splitWorktrees)"));
});

test("rec-room roster keeps space for recently visible resting leads that went active", () => {
  const layoutSource = readFileSync(
    join(__dirname, "../src/client/runtime/layout-source.ts"),
    "utf8"
  );
  const specSource = readFileSync(
    join(__dirname, "../../../docs/spec.md"),
    "utf8"
  );

  assert.match(
    layoutSource,
    /const effectiveLimit = Math\.max\(0, limit - reservedRecentLeadSlots\(snapshot\)\);/
  );
  assert.match(
    layoutSource,
    /slice\(0, effectiveLimit\);/
  );
  assert.match(
    specSource,
    /The rec area should keep at most the 4 most recent lead sessions visible;/,
  );
  assert.match(
    specSource,
    /If one of those visible resting leads becomes active again, older hidden leads should not pop back into the rec area just to fill that seat for a moment\./,
  );
});

test("runtime source limits visible rec-room resters to recent top-level leads", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(sceneSource.includes('const allRestingAgents = restingAgentsFor(snapshot, compact);'));
  assert.ok(sceneSource.includes('.filter((agent) =>\n            !agent.parentThreadId'));
  assert.ok(sceneSource.includes(".slice(0, 4);"));
  assert.ok(sceneSource.includes('const restingAssignments = stableSceneSlotAssignments(snapshot.projectRoot, "resting", restingAgents, 4);'));
});

test("runtime source can borrow recent rec-room leads for an empty selected workspace", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.ok(layoutSource.includes("function recentFallbackAgentsForEmptyProject(snapshot, allProjects, limit = SCENE_RECENT_LEAD_LIMIT) {"));
  assert.ok(layoutSource.includes('detail: projectPrefix + " · " + summary,'));
  assert.ok(layoutSource.includes('const fallbackAgents = recentFallbackAgentsForEmptyProject(snapshot, allProjects, recentLeadLimit);'));
  assert.ok(uiSource.includes('? viewSnapshot(selectedRawSnapshot, SCENE_RECENT_LEAD_LIMIT, rawProjects)'));
  assert.ok(uiSource.includes('? viewSessionSnapshot(selectedRawSnapshot, SESSION_RECENT_LEAD_LIMIT, rawProjects)'));
});

test("runtime source falls back to default rec layout when saved sofa columns overlap", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const settingsSource = readRuntimeSource("settings-source.ts");

  assert.ok(renderSource.includes("const defaultLayout = recRoomSofaLayout(compact, roomPixelWidth, baseY);"));
  assert.ok(renderSource.includes("{ ...defaultLayout.sofas[0], x: sofaColumns.left * tile, y: baseY }"));
  assert.ok(renderSource.includes("Math.abs(requestedLayout.sofas[1].x - requestedLayout.sofas[0].x) >= tile * 3"));
  assert.ok(renderSource.includes(": defaultLayout;"));
  assert.ok(renderSource.includes("const sofaWidth = Number(sofa?.sprite?.w) || layout.sofaWidth;"));
  assert.ok(renderSource.includes("const seatOffsetRatio = seatWithinSofa === 0 ? 0.18 : 0.62;"));
  assert.ok(settingsSource.includes("function stableSceneSlotAssignments(projectRoot, category, agents, maxSlots = null) {"));
  assert.ok(settingsSource.includes("|| (slotLimit !== null && slotIndex >= slotLimit)"));
  assert.ok(settingsSource.includes("if (slotLimit !== null && nextSlotIndex >= slotLimit) {"));
});

test("runtime source resolves facility providers and service tiles from startup scene definitions", () => {
  const renderSource = readRuntimeSource("render-source.ts");
  const sceneSource = readRuntimeSource("scene-source.ts");

  assert.ok(renderSource.includes("function sceneHeldItemDefinition(itemId) {"));
  assert.ok(renderSource.includes("function normalizeFurnitureFacilityProvider(item, roomWidthTiles) {"));
  assert.ok(renderSource.includes("function buildFacilityProviderModel(room, item) {"));
  assert.ok(renderSource.includes("const resolved = normalizeFurnitureItem({ ...item, column }, tileSize, room.width);"));
  assert.ok(sceneSource.includes("roomDoors: [],"));
  assert.ok(sceneSource.includes("facilities: [],"));
  assert.ok(sceneSource.includes("model.roomDoors.push({"));
  assert.ok(sceneSource.includes("model.facilities.push("));
});

test("runtime source animates sliding room doors and autonomous resting-item trips", () => {
  const sceneSource = readRuntimeSource("scene-source.ts");
  const navigationSource = readRuntimeSource("navigation-source.ts");

  assert.ok(sceneSource.includes('if (entry.autonomy && !entry.exiting && typeof renderer.updateAutonomousRestingMotion === "function") {'));
  assert.ok(sceneSource.includes('if (entry.kind === "thrown-item") {'));
  assert.ok(sceneSource.includes("renderer.roomDoorStates.forEach((doorState) => {"));
  assert.ok(sceneSource.includes("doorState.leftSprite.x = pixelSnap(doorState.baseLeftX - slide);"));
  assert.ok(navigationSource.includes("function updateAutonomousRestingMotion(motionState, now) {"));
  assert.ok(navigationSource.includes("spawnThrownHeldItem(previousState);"));
  assert.ok(navigationSource.includes("renderer.roomDoorStates.set(room.id, {"));
  assert.ok(navigationSource.includes("routeMotionStateTo("));
  assert.ok(navigationSource.includes("doorState.doorPulseUntil = performance.now() + sceneDoorConfig().holdOpenMs;"));
});

test("runtime source avoids doorway arrival animations for first-load historical sessions", () => {
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.ok(uiSource.includes("enteringAgentKeys = previousKeys.size === 0 || screenshotMode"));
  assert.ok(uiSource.includes("? new Set()"));
});

test("runtime source keeps current agents in the map scene even when they are between desk and rec placement states", () => {
  const layoutSource = readRuntimeSource("layout-source.ts");
  const seatingSource = readRuntimeSource("seating-source.ts");

  assert.ok(layoutSource.includes("function isLiveSceneAgent(agent) {"));
  assert.ok(layoutSource.includes("return shouldSeatAtWorkstation(agent) || agent.isCurrent === true;"));
  assert.ok(layoutSource.includes("const liveAgents = snapshot.agents.filter(isLiveSceneAgent);"));
  assert.ok(layoutSource.includes("const seenAgentIds = new Set();"));
  assert.match(
    seatingSource,
    /function isLiveSceneAgent\(agent\) {\n\s+if \(!agent \|\| agent\.source === "cloud" \|\| agent\.source === "presence"\) {\n\s+return false;\n\s+}\n\s+return shouldSeatAtWorkstation\(agent\) \|\| agent\.isCurrent === true;\n\s+}/
  );
});

test("toast renderer keeps the message, file-change, and command toast classes and chrome", () => {
  const toastSource = readFileSync(
    join(__dirname, "../src/client/toast-source.ts"),
    "utf8"
  );

  assert.ok(
    toastSource.includes('const className = \\`agent-toast \\${entry.kindClass}'),
    "toast className should start from the agent-toast base class"
  );
  assert.ok(
    toastSource.includes('entry.isFileChange ? " file-change" : ""'),
    "toast renderer should keep the file-change class toggle"
  );
  assert.ok(
    toastSource.includes('entry.isCommand ? " command-window" : ""'),
    "toast renderer should keep the command-window class toggle"
  );
  assert.ok(
    toastSource.includes('!entry.isCommand && Number(entry.priority) >= NOTIFICATION_PRIORITY_MESSAGE ? " message-toast" : ""'),
    "toast renderer should keep the message-toast class toggle"
  );
  assert.ok(
    toastSource.includes('isTextMessageNotification(entry) ? " text-message-toast" : ""'),
    "toast renderer should keep the text-message-toast class toggle"
  );
  assert.ok(
    toastSource.includes('<div class="agent-toast-window-label">cmd.exe</div>'),
    "command toasts should keep the cmd.exe window chrome"
  );
  assert.ok(
    toastSource.includes('<div class="agent-toast-command-line">'),
    "command toasts should keep per-line command rendering"
  );
  assert.ok(
    toastSource.includes('<span class="agent-toast-delta add">+\\${line.linesAdded}</span>'),
    "file-change toasts should keep added-line deltas"
  );
  assert.ok(
    toastSource.includes('<span class="agent-toast-delta remove">-\\${line.linesRemoved}</span>'),
    "file-change toasts should keep removed-line deltas"
  );
});

test("toast runtime preserves read command summaries and text-message priority", () => {
  const renderSource = readRuntimeSource("render-source.ts");

  assert.match(
    renderSource,
    /if \(executable === "sed" \|\| executable === "cat" \|\| executable === "head" \|\| executable === "tail" \|\| executable === "less" \|\| executable === "more" \|\| executable === "bat"\) {\n\s+title = "Read " \+ firstPathLabel;/,
  );
  assert.match(
    renderSource,
    /else if \(executable === "rg" \|\| executable === "grep"\) {\n\s+title =\n\s+pathTokens\.length > 1 \? "Exploring " \+ pathTokens\.length \+ " files"\n\s+: firstPath \? "Search " \+ firstPathLabel\n\s+: "Search files";/,
  );
  assert.match(
    renderSource,
    /else if \(executable === "ls" \|\| executable === "find" \|\| executable === "tree"\) {\n\s+title =\n\s+pathTokens\.length > 1 \? "Exploring " \+ pathTokens\.length \+ " files"\n\s+: firstPath \? "Explore " \+ cleanReportedPath\(snapshot\.projectRoot, firstPath\)\n\s+: "Explore files";/,
  );
  assert.ok(
    renderSource.includes("if (latestMessageChanged) {\n          return {"),
    "latest message changes should still build a notification descriptor"
  );
  assert.ok(
    renderSource.includes('isTextMessage: true'),
    "latest message notifications should still be marked as text messages"
  );
  assert.ok(
    renderSource.includes('priority: NOTIFICATION_PRIORITY_MESSAGE'),
    "latest message notifications should still use message priority"
  );
});

test("typed snapshot events still allow message toasts even when the agent is no longer current", () => {
  const toastSource = readFileSync(
    join(__dirname, "../src/client/toast-source.ts"),
    "utf8"
  );

  assert.match(
    toastSource,
    /if \(\n?\s*!agent\.isCurrent\n?\s*&& agent\.state !== "waiting"\n?\s*&& agent\.state !== "blocked"\n?\s*&& event\.kind !== "message"\n?\s*&& !\(event\.kind === "tool" && event\.itemType === "webSearch"\)\n?\s*\) \{/,
  );
});

test("boss relationship arrows are hover-only curved overlays with arrowheads", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const specSource = readFileSync(
    join(__dirname, "../../../docs/spec.md"),
    "utf8"
  );

  assert.ok(navigationSource.includes(".bezierCurveTo(control1X, control1Y, control2X, control2Y, line.x2, line.y2)"));
  assert.ok(navigationSource.includes("const arrowHead = new PIXI.Graphics()"));
  assert.ok(navigationSource.includes("state.hoveredRelationshipBossKey"));
  assert.match(
    specSource,
    /Boss-to-subagent relationship arrows should only appear when the user is hovering or focusing that boss in the scene;/,
  );
});

test("spec defines door-based arrivals and departures for visible agents", () => {
  const specSource = readFileSync(
    join(__dirname, "../../../docs/spec.md"),
    "utf8"
  );

  assert.match(
    specSource,
    /A newly visible active agent should enter from the room door and walk to its assigned workstation\./,
  );
  assert.match(
    specSource,
    /If a resting lead becomes active again, it should leave its rec-area seat and walk to its newly assigned workstation instead of despawning and respawning\./,
  );
  assert.match(
    specSource,
    /When an agent truly leaves the visible scene, it should walk back out through the room door\./,
  );
});

test("runtime source only animates exit ghosts for explicit departures and dedupes them", () => {
  const navigationSource = readRuntimeSource("navigation-source.ts");
  const uiSource = readRuntimeSource("ui-source.ts");

  assert.ok(navigationSource.includes("const departingAgentKeys = new Set(departingAgents.map((agent) => agent.key));"));
  assert.ok(navigationSource.includes("!motionState || currentAgentKeys.has(key) || motionState.exiting || !departingAgentKeys.has(key)"));
  assert.ok(uiSource.includes("const existingGhost = departingAgents.find((ghost) => ghost.key === key) || null;"));
  assert.ok(uiSource.includes("existingGhost.expiresAt = now + DEPARTING_AGENT_TTL_MS;"));
});
